# Basic site settings
title: Assignment 2 (24S2-SC4052-CLOUD COMPUTING) (Building an AI-Enhanced Codebase Analyzer using GitHub APIs and LLMs)

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Navigation
nav_sort: case_sensitive

# Aux links (shown in upper right)
aux_links:
  "View on GitHub":
    - "https://github.com/tej172/cloud_indv_assignments/tree/main/ass_2"
    
# Color scheme
color_scheme: light

# Author settings 
author:
    name: Teg Singh Tiwana 
    studentID: U2122816B
    url: https://github.com/tej172
    github: tej172

# Mermaid settings (Visualizing with AI | AI diagramming)
# This is the default mermaid version, you can change it to the version you want
# You can also use the latest version by using the following line
# mermaid: latest
# You can also use the following line to use a specific version
# mermaid: 9.1.3
# Create charts and diagrams and share them with your whole team using Mermaid Chart pro
mermaid:
  version: "9.1.3"  # can chnage to the version you want
  # Default configuration
  config: |
    directionLR

# Callouts settings
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  best-practice:
    title: Best Practice
    color: green
  
# The custom navigation
nav:
  - Home: index.md       # Link to your main docs index
  - GitHub: "https://github.com/tej172/cloud_indv_assignments/tree/main/ass_2"
